apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-pvc
  namespace: tomcat  # 네임스페이스가 tomcat으로 설정되어 있어야 합니다.
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # PVC의 스토리지 요청 크기 조정
