services:
  proxy:
    build: ./proxy
    image: bluegreen/proxy:v1
    pull_policy: build
    container_name: bluegreen-proxy
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - bluegreen-net

networks:
  bluegreen-net:
    external: true
    name: bluegreen-net
