version: '3'
services:
  nginx-blue:
    image: nginx:latest
    container_name: nginx-blue
    user: root  # 루트 사용자로 Nginx 실행
    volumes:
      - /tmp/blue:/usr/share/nginx/html:ro
      - /conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    networks:
      - bluegreen-net

  nginx-green:
    image: nginx:latest
    container_name: nginx-green
    user: root  # 루트 사용자로 Nginx 실행
    volumes:
      - /tmp/green:/usr/share/nginx/html:ro
      - /conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:80"
    networks:
      - bluegreen-net

networks:
  bluegreen-net:
    driver: bridge
