apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tomcat
  namespace: tomcat
spec:
  to:
    kind: Service
    name: tomcat-service  # tomcat-service로 라우팅
  port:
    targetPort: 8080  # Tomcat의 기본 포트 8080
  tls:
    termination: edge
  wildcardPolicy: None
