apiVersion: v1
kind: Service
metadata:
  name: tomcat 
  namespace: tomcat 
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 50000
    targetPort: 50000
    protocol: TCP
    name: agent
  selector:
    app: tomcat 
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tomcat
  namespace: tomcat
spec:
  to:
    kind: Service
    name: tomcat
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
