apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-green
  namespace: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
      version: green
  template:
    metadata:
      labels:
        app: tomcat
        version: green
    spec:
      containers:
      - name: tomcat
        image: "bastion.cwokd.com:444/tomcat:v6.6"  # 그린 버전의 이미지
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tomcat-storage
          mountPath: "/opt/tomcat"
      volumes:
      - name: tomcat-storage
        persistentVolumeClaim:
          claimName: tomcat-pvc
      securityContext:
        runAsUser: 0
      imagePullSecrets:
      - name: regsecret
